# Generated by Django 4.2.3 on 2023-07-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extrato',
            new_name='Valores',
        ),
    ]
