# Generated by Django 4.2.3 on 2023-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
